### ISSUE TITLE
Flatpickr does not initialize properly in production

### ISSUE THREAD

**Issue by aroy314** [haoxins/react-flatpickr#146]
I'm using React Flatpickr in a component that works perfectly on my dev environment (node v14.15.4) but not on production (v14.15.4)

Here are the errors in console : 
`ReferenceError: Cannot access uninitialized variable.`
`TypeError: e.flatpickr.setDate is not a function. (In 'e.flatpickr.setDate(e.props.value,!1)', 'e.flatpickr.setDate' is undefined)`
Here is a screenshot of the console : 
![Capture d’écran 2021-02-02 à 11 31 40](https://user-images.githubusercontent.com/14325646/106587710-3a98a680-654a-11eb-9599-a9c4959e8c1e.png)

After having a deeper look into the uglyfied code, I found out the bug comes from the internal code of flatpickr and not from my code. The weird thing is that I'm using Flatpickr on other projects in production the same way I do here, and it's perfectly working ! All of them are on the following version in package.json : `"react-flatpickr": "^3.10.6"`

Here is the code of my component (simplified and still not working) : 
```javascript
import React, { Component } from 'react'
import Flatpickr from 'react-flatpickr'
import moment from 'moment'

export default class CalendarPickrSimple extends Component {
	constructor(props) {
		super(props)
		this._onSelect = this.onSelect.bind(this)
	}

	onSelect([value]) {
		if (value) {
			this.props.onSelect(moment(value))
		}
	}

	render() {
		const {value} = this.props
		const options = {
			onClose: this._onSelect
		}

		return <div>
			<Flatpickr
				value={value ? moment(value) : moment()}
				options={options}
				style={{
					width: '100%',
					position: 'relative'
				}}
			/>
		</div>
	}
}
```

I'm using webpack 4.46 and babel 7.12 (and its many plugins) for building my assets. 
Concerning webpack config, the difference between prod and dev config is the use of `uglify-es-webpack-plugin` in prod and `HotModuleReplacementPlugin` in dev. 
The .babelrc config is identical in dev and prod, the only difference is the plugin `react-hot-loader/babel` in dev.

I have no idea if I should post my message here or in the main flatpickr repo. Let me know if I need to. 
I can provide more details if necessary.
Thanks for your help !

**Comment by jacobmischka** [comment]
Weird, it looks like `componentDidMount` isn't getting called for some reason. It looks like `uglify-es-webpack-plugin` is deprecated, can you try the recommended `uglifyjs-webpack-plugin` instead to see if that makes a difference?

I haven't experienced this myself in any production builds recently, and nothing has been changed in this component in quite a while.

**Comment by jacobmischka** [comment]
Can you dig into that `ReferenceError` at the top a bit to see exactly what variable it's referring to? Is it `e.flatpickr`? Or something else?

**Comment by aroy314** [comment]
Hi @jacobmischka ! 
Thanks for your help, I dug deeper in the `ReferenceError`, but the code is very obfuscated, have a look on the two first functions in the call stack : 
![Capture d’écran 2021-02-04 à 17 30 46](https://user-images.githubusercontent.com/14325646/106924442-5c8f5600-670f-11eb-9298-41554087263d.png)
![Capture d’écran 2021-02-04 à 17 31 09](https://user-images.githubusercontent.com/14325646/106924446-5e591980-670f-11eb-8dbc-97698413fcfb.png)
![Capture d’écran 2021-02-04 à 17 31 28](https://user-images.githubusercontent.com/14325646/106924448-5e591980-670f-11eb-9134-e6b6f7d0e3e2.png)

I wanted to change `uglify-es-webpack-plugin` but found out that `uglifyjs-webpack-plugin` is also deprecated, so I went directly to `terser-webpack-plugin ^4.2.3`. After configuring it and building a new version in prod, everything seems to be working 🍾

Thank you for your help !

**Comment by kailashvele** [comment]
Still facing the error in Laravel Mix.
