### ISSUE TITLE
Bump react-flatpickr from 4.0.1 to 4.0.3: flatpickr ref issue

### ISSUE THREAD

**Issue by okhomenko** [haoxins/react-flatpickr#247]
Have a few issues post 4.0.3 upgrade

1.

```tsx
import Flatpickr from 'react-flatpickr';
```

<img width="903" alt="Image" src="https://github.com/user-attachments/assets/537990d1-94fa-4ee8-a15b-0bd370a12888" />

2.
```bash
error TS2322: Type '(dates: Date[], dateString: string) => void' is not assignable to type 'ChangeEventHandler<HTMLInputElement>'
```

Before 4.0.3 everything worked on 4.0.1 with @types/react-flatpickr@3.8.11

**Comment by jasonsyoung** [comment]
I'll take a look at this tomorrow

**Comment by jasonsyoung** [comment]
ok, i have published a new release 4.0.4. You can use the new type `DateTimePickerHandle` and use that type for your ref, like this:

```
const startInput = useRef<DateTimePickerHandle>(undefined);

startInput.current?.flatpickr?.open();
```

**Comment by okhomenko** [comment]
I see that you added export
https://github.com/haoxins/react-flatpickr/blob/master/types/react-flatpickr.d.ts#L33-L35

but `types/` directory is not part of the bundled npm package

<img width="201" alt="Image" src="https://github.com/user-attachments/assets/05beb148-9758-4393-b24e-2122e191f502" />

<img width="564" alt="Image" src="https://github.com/user-attachments/assets/71dc479b-f07f-4671-8152-4a76192ca8e9" />

**Comment by jasonsyoung** [comment]
@okhomenko i am not a typescript expert -- do you know why my config is not exporting those? it seems to only default export `DateTimePickerProps`, but it doesn't export the rest that are defined in the types/ file.

**Comment by jasonsyoung** [comment]
i did a hack to get them exported
